# Uncomment the next line to define a global platform for your project
  platform :ios, '11.0'

  use_frameworks!

target 'ZHKSwiftExtension_Example' do
  pod 'ZHKSwiftExtension', :path => '../'

end
